version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - 8000:8000 
    volumes:
      - ./admin:/app
    restart: always  
    command: 'python manage.py runserver 0.0.0.0:8000'  
    depends_on:
      - admin_db
      - rabbitmq
      - admin_queue

  admin_queue:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: always
    command: 'python consumer.py' 
    depends_on:
    - admin_db
    - rabbitmq   

  admin_db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./admin/.dbdata:/var/lib/mysql
    ports:
      - 33066:3306      

  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - 8001:5000
    volumes:
      - ./main:/app
    restart: always  
    command: 'python main.py'  
    depends_on:
      - main_db
      - rabbitmq
      - main_queue

  main_queue:
    build:
      context: ./main
      dockerfile: Dockerfile
    command: 'python consumer.py' 
    restart: always
    depends_on:
    - main_db
    - rabbitmq   

  main_db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./main/.dbdata:/var/lib/mysql
    ports:
      - 33067:3306      
